// Chapter 5 content data — sourced directly from the 2026 SCERT textbook chapter.
// Structure: each section has an id (for nav anchors) and a list of "blocks" rendered in order.
const CH5_DATA = {
  sections: [
    {
      id: "intro", kicker: "5.1 – 5.2", title: "Control Structures",
      lede: "We have already studied Python elements, including lists, tuples and sets. For efficient utilisation of Python elements and sequences, control structures are essential.",
      blocks: [
        { type: "text", text: "Control structures determine the flow of execution of instructions. They allow decision-making, looping and branching based on conditions. Python also provides powerful data structures to store and manipulate collections of data efficiently." },
        { type: "text", text: "Control structures are methods that dictate the flow of execution in a program. They answer the question: \u201cWhat should happen next in a program?\u201d Normally, a program executes instructions one after another in the order they appear. Statements or instructions executed together are called a code block. In Python, indentation — the use of whitespace at the beginning of a line — is the only way to define a code block. It is mandatory and directly affects how the code executes." },
        { type: "callout", text: "Major applications: Decision Making · Flow Control · Iterations · Improved Efficiency and Flexibility · Real-World Applications." },
      ],
    },
    {
      id: "conditionals", kicker: "5.2.1", title: "Conditional Statements",
      lede: "if-elif-else and match-case — how Python programs make decisions.",
      blocks: [
        { type: "sub", text: "(a) if-elif-else Statement" },
        { type: "text", text: "The if-elif-else control structure is used to make decisions in a Python program based on conditions. It allows the program to evaluate multiple expressions and execute a block of code depending on which condition is true." },
        { type: "list", items: [
          "The if statement checks the first condition.",
          "If the if condition is false, the elif (else if) statement checks another condition.",
          "If neither the if nor any elif condition is true, the else block is executed.",
          "Multiple elif branches are allowed. Only one else branch is allowed, and it must come last.",
          "Usage of elif or else is NOT compulsory with every if-elif-else structure.",
        ]},
        { type: "syntax", lines: ["if condition:", "    code block/statement", "elif condition:", "    code block/statement", "else:", "    code block/statement"] },
        { type: "example", num: "5.1", title: "Grading with if-elif-else",
          code: 'marks = int(input("Enter marks: "))\nif marks >= 90:\n    print("Grade A+")\nelif marks >= 80:\n    print("Grade A")\nelif marks >= 70:\n    print("Grade B+")\nelif marks >= 60:\n    print("Grade B")\nelif marks >= 50:\n    print("Grade C+")\nelif marks >= 40:\n    print("Grade C")\nelif marks >= 30:\n    print("Grade D+")\nelse:\n    print("Grade D")',
          output: "Enter marks: 91\nGrade A+",
          explain: "The if-elif-else structure ensures only ONE block runs, even if several conditions would be true. Click Run — the program will prompt you for marks in a popup." },
        { type: "sub", text: "(b) Match-Case Statement" },
        { type: "text", text: "Python introduced the match-case statement in version 3.10 as part of its structural pattern matching feature — an alternative to switch (C++, Java, JavaScript). It compares a value, termed pattern, against multiple cases and executes code based on the first matching case." },
        { type: "list", items: ["match evaluates the variable.", "Each case checks for a specific pattern.", "The _ (underscore) acts as a default case."] },
        { type: "syntax", lines: ["match variable:", "    case pattern1:", "        # code block", "    case pattern2:", "        # code block", "    case _:", "        # default block"] },
        { type: "example", num: "5.2", title: "match-case in Action",
          code: 'day = "Monday"\nmatch day:\n    case "Monday":\n        print("Start of the week")\n    case "Friday":\n        print("Weekend is near")\n    case _:\n        print("Regular day")',
          output: "Start of the week",
          explain: "match compares day against each case in order and runs the first matching block. Try editing day to \"Friday\" or something else and re-run!" },
        { type: "callout", text: "Benefits of match-case: cleaner and more readable than long if-elif-else chains; supports advanced pattern matching; enhances code maintainability." },
        { type: "quiz", items: [
          ["Which branch of if-elif-else must always come last, if used?", "else"],
          ["Which symbol represents the default case in match-case?", "_ (underscore)"],
          ["Is elif or else compulsory with every if statement?", "No — both optional"],
        ]},
      ],
    },
    {
      id: "loops", kicker: "5.2.2", title: "Looping Statements",
      lede: "for loops, while loops, break, continue, and the else clause.",
      blocks: [
        { type: "text", text: "Looping lets a set of instructions execute repeatedly until a certain condition is met. A loop checks a condition before or after executing a block of code — while the condition is true, the loop body runs; once it becomes false, the loop stops automatically." },
        { type: "sub", text: "(i) for loop" },
        { type: "text", text: "A for loop in Python is used to iterate over a sequence (like a list or string) and perform actions on each item in that sequence. It's like saying, \u201cdo something for each item in this group.\u201d" },
        { type: "syntax", lines: ["for loop_variable in sequence:", "    # do required operation with loop_variable"] },
        { type: "list", items: [
          "loop_variable takes the value of each element in the sequence, one at a time.",
          "sequence is the collection being iterated over.",
          "How it works: Python looks at the first item, assigns it to loop_variable, runs the code inside the loop, moves to the next item and repeats — when all items are processed, the loop ends.",
        ]},
        { type: "example", num: "5.3", title: "Looping Through a String",
          code: 'word = "hello"\nfor letter in word:\n    print(letter)', output: "h\ne\nl\nl\no",
          explain: "Strings are sequences of characters, so a for loop can iterate through them character by character." },
        { type: "sub", text: "Using range()" },
        { type: "text", text: "range(start, stop, step) generates a sequence of numbers. start defaults to 0, stop is not inclusive, step defaults to 1." },
        { type: "example", num: "5.4", title: "for Loop with range()",
          code: 'for i in range(1, 6):\n    print(i)', output: "1\n2\n3\n4\n5",
          explain: "range(1, 6) generates 1, 2, 3, 4, 5 — the stop value 6 itself is never included." },
        { type: "text", text: "Nested for loops: you can place one for loop inside another. It's like a clock — the hour hand moves slowly (outer loop) while the minute hand moves faster (inner loop), completing a full circle for each hour." },
        { type: "example", num: "5.5", title: "Using a Nested Loop",
          code: 'for i in range(1, 4):\n    for j in range(1, 4):\n        print(i, "*", j, "=", i * j)',
          output: "1 * 1 = 1\n1 * 2 = 2\n1 * 3 = 3\n2 * 1 = 2\n2 * 2 = 4\n2 * 3 = 6\n3 * 1 = 3\n3 * 2 = 6\n3 * 3 = 9",
          explain: "For each value of i, the inner loop runs completely through j — 3 x 3 = 9 total iterations." },
        { type: "sub", text: "Controlling the loop: break and continue" },
        { type: "list", items: [
          "break — used inside loops to immediately stop the loop when a certain condition is met.",
          "continue — skips the current iteration and moves to the next one, without stopping the loop entirely.",
        ]},
        { type: "example", num: "5.6", title: "Using break",
          code: 'for num in range(1, 10):\n    if num == 5:\n        break\n    print(num)', output: "1\n2\n3\n4",
          explain: "The loop stops the instant num equals 5 — it never even reaches print(5)." },
        { type: "example", num: "5.7", title: "Using continue",
          code: 'for num in range(1, 6):\n    if num == 3:\n        continue\n    print(num)', output: "1\n2\n4\n5",
          explain: "3 is skipped, but the loop keeps running through the remaining values." },
        { type: "example", num: "5.8", title: "Counting Vowels in a String",
          code: 'sentence = "Python is fun"\nvowels = "aeiou"\ncount = 0\nfor char in sentence:\n    if char.lower() in vowels:\n        count += 1\nprint("Number of vowels:", count)',
          output: "Number of vowels: 3", explain: "char.lower() normalises case before checking membership in the vowels string." },
        { type: "example", num: "5.9", title: "for Loop with else",
          code: 'for i in range(3):\n    print("Loop:", i)\nelse:\n    print("Loop finished")',
          output: "Loop: 0\nLoop: 1\nLoop: 2\nLoop finished",
          explain: "Python allows an else clause with a for loop — it runs after the loop finishes normally." },
        { type: "quiz", items: [
          ["What does range(1, 6) generate?", "1, 2, 3, 4, 5"],
          ["Which statement skips only the current iteration?", "continue"],
          ["Which statement stops the loop immediately?", "break"],
          ["When does a for-loop's else block run?", "After the loop finishes normally"],
        ]},
        { type: "sub", text: "(ii) while loop" },
        { type: "text", text: "A while loop in Python is used to execute a block of code repeatedly based on a specified condition. The condition is evaluated before each iteration; once it becomes False, the loop terminates." },
        { type: "syntax", lines: ["while condition:", "    block of code"] },
        { type: "example", num: "5.10", title: "Basic while Loop",
          code: 'count = 1\nwhile count <= 5:\n    print("Count is:", count)\n    count += 1',
          output: "Count is: 1\nCount is: 2\nCount is: 3\nCount is: 4\nCount is: 5",
          explain: "The loop runs 5 times. When count becomes 6, count <= 5 evaluates to False and the loop terminates." },
        { type: "example", num: "5.11", title: "Infinite Loops — A Warning",
          code: 'i = 1\nwhile i < 5:\n    print("i =", i)   # Missing increment\n                       # statement in the block',
          output: null,
          explain: "An infinite loop occurs when the condition never becomes False — usually because the loop control variable is not updated correctly. We haven't wired this one to Run, on purpose — it really would run forever!",
          noRun: true },
        { type: "example", num: "5.12", title: "while Loop with break",
          code: 'i = 1\nwhile i <= 10:\n    print(i)\n    if i == 5:\n        break\n    i += 1', output: "1\n2\n3\n4\n5",
          explain: "break exits the while loop prematurely, even though the condition i <= 10 is still True." },
        { type: "example", num: "5.13", title: "while Loop with continue",
          code: 'i = 0\nwhile i < 6:\n    i += 1\n    if i == 3:\n        continue\n    print(i)', output: "1\n2\n4\n5\n6",
          explain: "When i is 3, continue skips the print(i) line for that pass only." },
        { type: "example", num: "5.14", title: "while Loop with else",
          code: 'i = 0\nwhile i < 4:\n    print("i =", i)\n    i += 1\nelse:\n    print("Loop finished")',
          output: "i = 0\ni = 1\ni = 2\ni = 3\nLoop finished",
          explain: "As with for, the else block of a while loop executes once the condition becomes False." },
        { type: "example", num: "5.15", title: "Nested while Loop",
          code: 'i = 1\nwhile i <= 3:\n    j = 1\n    while j <= 2:\n        print(f"i = {i}, j = {j}")\n        j += 1\n    i += 1',
          output: "i = 1, j = 1\ni = 1, j = 2\ni = 2, j = 1\ni = 2, j = 2\ni = 3, j = 1\ni = 3, j = 2",
          explain: "A while loop can be nested inside another while loop, just like for loops." },
        { type: "text", text: "Practical applications: user input validation, menu-driven programs, game loops. Tips: always ensure the loop condition will eventually become False; use break and continue judiciously; avoid infinite loops unless intentionally required." },
        { type: "quiz", items: [
          ["What causes an infinite loop?", "Condition never becomes False"],
          ["When does a while-loop's else block execute?", "When the condition becomes False"],
          ["Name two practical uses of a while loop.", "Input validation, menu-driven programs"],
        ]},
      ],
    },
    {
      id: "lists", kicker: "5.3", title: "Lists",
      lede: "Ordered, mutable, allow duplicates — Python's most flexible collection.",
      blocks: [
        { type: "list", items: [
          "Ordered: items have a defined order that won't change unless explicitly modified.",
          "Mutable: elements can be added, removed, or modified after creation.",
          "Allow duplicates: the same value can be repeated in a list.",
          "Indexed: each item has a unique index starting from 0.",
          "Python lists are created using square brackets [ ].",
        ]},
        { type: "example", num: "5.16", title: "Creating Lists",
          code: 'fruits = ["apple", "banana", "cherry"]\n\nempty_list = []\n\nmixed = [1, "hello", 3.14, True]\nprint(fruits, empty_list, mixed)',
          output: null, explain: "Lists can hold mixed data types — integers, strings, floats, booleans, even other lists." },
        { type: "example", num: "5.17", title: "Accessing List Elements",
          code: 'fruits = ["apple", "banana", "cherry"]\nprint(fruits[0])\nprint(fruits[2])\nprint(fruits[-1])',
          output: "apple\ncherry\ncherry", explain: "Negative indexing allows access from the end of the list." },
        { type: "example", num: "5.18", title: "Slicing Lists",
          code: 'numbers = [10, 20, 30, 40, 50]\nprint(numbers[1:4])', output: "[20, 30, 40]",
          explain: "Slicing syntax is list[start:stop:step] — the stop index itself is excluded." },
        { type: "example", num: "5.19", title: "Modifying Lists",
          code: 'fruits = ["apple", "banana", "cherry"]\nfruits[1] = "blueberry"\nprint(fruits)',
          output: "['apple', 'blueberry', 'cherry']", explain: "Lists are mutable, so individual elements can be reassigned directly by index." },
        { type: "text", text: "Adding elements: append() adds to the end; insert() adds at a specific index; extend() adds items from another list. Removing elements: remove() removes the first occurrence of a value; pop() removes an item at a given index; clear() removes all items." },
        { type: "methodsTable", headers: ["Method","Description"], rows: [
          ["append()","Adds an item to the end"], ["insert()","Inserts item at specified index"],
          ["extend()","Adds multiple items"], ["remove()","Removes first occurrence of item"],
          ["pop()","Removes item at index"], ["clear()","Removes all items"],
          ["index()","Returns index of first occurrence"], ["count()","Returns number of occurrences"],
          ["sort()","Sorts the list in ascending order"], ["reverse()","Reverses the list"],
          ["copy()","Returns a shallow copy of the list"],
        ]},
        { type: "example", num: "5.20", title: "Application: Student Marks",
          code: 'marks = [85, 90, 78, 92]\naverage = sum(marks) / len(marks)\nprint("Average marks:", average)',
          output: "Average marks: 86.25", explain: "sum() and len() together give a quick way to compute an average from a list." },
        { type: "example", num: "5.21", title: "Application: Shopping List",
          code: 'shopping = []\nshopping.append("milk")\nshopping.append("bread")\nshopping.append("eggs")\nprint(shopping)',
          output: "['milk', 'bread', 'eggs']", explain: "Starting from an empty list and building it up with append() is a very common pattern." },
        { type: "example", num: "5.22", title: "Application: Removing Duplicates",
          code: 'items = ["apple", "banana", "apple", "orange"]\nunique_items = []\nfor item in items:\n    if item not in unique_items:\n        unique_items.append(item)\nprint(unique_items)',
          output: "['apple', 'banana', 'orange']", explain: "Each item is only appended if it isn't already present in unique_items." },
        { type: "example", num: "5.23", title: "List Comprehension",
          code: 'squares = [x*x for x in range(1, 6)]\nprint(squares)', output: "[1, 4, 9, 16, 25]",
          explain: "List comprehension provides a concise way to build a list from a loop expression in a single line." },
        { type: "example", num: "5.24", title: "Nested Lists",
          code: 'matrix = [[1, 2], [3, 4], [5, 6]]\nprint(matrix[1][0])', output: "3",
          explain: "Lists can contain other lists — matrix[1][0] selects the 2nd inner list, then its 1st item." },
        { type: "quiz", items: [
          ["What is the index of the first element in a list?", "0"],
          ["Which method removes all elements from a list?", "clear()"],
          ["Which method adds elements from another list?", "extend()"],
          ["What does list[1:4] return from [10,20,30,40,50]?", "[20, 30, 40]"],
        ]},
      ],
    },
    {
      id: "tuples", kicker: "5.4", title: "Tuples",
      lede: "Ordered, immutable — perfect for fixed collections of data.",
      blocks: [
        { type: "text", text: "A tuple is like a list but immutable — its contents cannot be changed once created. Ideal for fixed data such as coordinates or configuration settings." },
        { type: "example", num: null, title: "Creating Tuples",
          code: 'fruits = ("apple", "banana", "cherry")\nnumbers = (10, 20, 30)\n\ncolors = "red", "green", "blue"   # parentheses optional\n\nempty = ()\nsingle = ("apple",)   # trailing comma needed for one item\nprint(fruits, numbers, colors, empty, single)',
          output: null, explain: null },
        { type: "example", num: "5.25", title: "Accessing Tuple Elements",
          code: 'fruits = ("apple", "banana", "cherry")\nprint(fruits[0])\nprint(fruits[-1])', output: "apple\ncherry",
          explain: "Indexing works exactly as it does for lists — including negative indices." },
        { type: "example", num: "5.26", title: "Slicing Tuples",
          code: 'numbers = (10, 20, 30, 40, 50)\nprint(numbers[1:4])\nprint(numbers[::2])', output: "(20, 30, 40)\n(10, 30, 50)",
          explain: "numbers[::2] uses a step of 2, taking every second element across the whole tuple." },
        { type: "example", num: "5.27", title: "Concatenation & Repetition",
          code: 'a = (1, 2)\nb = (3, 4)\nc = a + b\nprint(c)\n\nrepeat = ("Hi",) * 3\nprint(repeat)',
          output: "(1, 2, 3, 4)\n('Hi', 'Hi', 'Hi')", explain: "Although tuples are immutable, + and * create brand-new tuples rather than modifying the originals." },
        { type: "text", text: "Tuples support in / not in, len(), and looping exactly like lists — only modification is disallowed. Tuples have only two built-in methods, because they're immutable:" },
        { type: "methodsTable", headers: ["Method","Description"], rows: [
          ["count()","Returns the number of times a value appears"],
          ["index()","Returns the index of the first occurrence"],
        ]},
        { type: "example", num: "5.28", title: "Tuple Methods",
          code: 'numbers = (1, 2, 3, 2, 2)\nprint(numbers.count(2))\nprint(numbers.index(3))', output: "3\n2", explain: null },
        { type: "quiz", items: [
          ["Why is a tuple called immutable?", "Its contents cannot change after creation"],
          ["What syntax creates a single-element tuple?", 'A trailing comma: ("apple",)'],
          ["Name the two built-in tuple methods.", "count(), index()"],
        ]},
      ],
    },
    {
      id: "sets", kicker: "5.5", title: "Sets",
      lede: "Unordered, unindexed, no duplicates — built for membership and set operations.",
      blocks: [
        { type: "list", items: [
          "Unordered: items don't have a guaranteed order and may appear differently each time.",
          "Unindexed: elements cannot be accessed using indices like lists or tuples.",
          "No duplicates: sets automatically remove duplicate values.",
          "Immutable elements: set members must be immutable (numbers, strings, tuples).",
          "Mutable container: while elements are immutable, the set itself can have items added or removed.",
        ]},
        { type: "example", num: null, title: "Creating Sets",
          code: 'fruits = {"apple", "banana", "cherry"}\nnumbers = {1, 2, 3, 4}\n\ncolors = set(["red", "green", "blue"])\nempty = set()   # NOT {} — that creates a dictionary\n\nitems = {"apple", "banana", "apple"}\nprint(items)',
          output: "{'apple', 'banana'}", explain: "Sets are built with { } or set(); creating one from duplicate values automatically removes the repeats." },
        { type: "example", num: "5.29", title: "Looping & Adding Elements",
          code: 'fruits = {"apple", "banana", "cherry"}\nfor fruit in fruits:\n    print(fruit)\n\nfruits.add("orange")\nfruits.update(["kiwi", "melon"])\nprint(fruits)',
          output: "apple\ncherry\nbanana\n{'apple', 'cherry', 'banana', 'orange', 'kiwi', 'melon'}",
          explain: "Since sets are unordered, printed order can vary. add() inserts one item; update() inserts several." },
        { type: "text", text: "Removing elements: remove() raises an error if the item is missing; discard() does not — the safer choice when unsure. pop() removes a random element; clear() empties the set." },
        { type: "example", num: "5.30", title: "Set Operations — Union & Intersection",
          code: 'a = {1, 2, 3}\nb = {3, 4, 5}\nprint(a | b)   # union\nprint(a & b)   # intersection\nprint(a - b)   # difference\nprint(a ^ b)   # symmetric difference',
          output: "{1, 2, 3, 4, 5}\n{3}\n{1, 2}\n{1, 2, 4, 5}",
          explain: "|, &, -, ^ mirror mathematical set operations: union, intersection, difference, symmetric difference." },
        { type: "methodsTable", headers: ["Method","Description"], rows: [
          ["add()","Adds a single element"], ["update()","Adds multiple elements"],
          ["remove()","Removes specified element (error if not found)"],
          ["discard()","Removes specified element (no error)"], ["pop()","Removes a random element"],
          ["clear()","Removes all elements"], ["union()","Returns union of sets"],
          ["intersection()","Returns common elements"],
          ["difference()","Returns elements in one set but not the other"],
          ["symmetric_difference()","Returns elements in either set but not both"],
          ["issubset()","Checks if one set is a subset of another"],
          ["issuperset()","Checks if one set is a superset of another"],
          ["isdisjoint()","Checks if sets have no common elements"],
        ]},
        { type: "example", num: "5.31", title: "Application: Removing Duplicates & Set Ops",
          code: 'names = ["Alice", "Bob", "Alice", "Charlie"]\nunique_names = set(names)\nprint(unique_names)\n\na = {"apple", "banana", "cherry"}\nb = {"banana", "kiwi", "melon"}\nprint("Union:", a.union(b))\nprint("Intersection:", a.intersection(b))\nprint("Difference:", a.difference(b))',
          output: "{'Alice', 'Bob', 'Charlie'}\nUnion: {'cherry', 'kiwi', 'apple', 'melon', 'banana'}\nIntersection: {'banana'}\nDifference: {'cherry', 'apple'}",
          explain: "Converting a list to a set is a one-line way to remove duplicates, since sets never allow repeats." },
        { type: "example", num: "5.32", title: "Checking Subsets",
          code: 'x = {1, 2}\ny = {1, 2, 3, 4}\nprint(x.issubset(y))', output: "True",
          explain: "issubset() checks whether every element of x also appears in y." },
        { type: "quiz", items: [
          ["Which data structure does NOT allow duplicates?", "Set"],
          ["What does a & b represent for two sets?", "Intersection"],
          ["remove() vs discard() — which raises an error if missing?", "remove()"],
        ]},
      ],
    },
    {
      id: "dicts", kicker: "5.6", title: "Dictionaries",
      lede: "Key–value pairs — fast lookup, insertion, and deletion.",
      blocks: [
        { type: "list", items: [
          "Unordered before Python 3.7; from 3.7 onwards, dictionaries preserve insertion order.",
          "Mutable: keys and values can be added, updated or removed after creation.",
          "Unique keys: repeating a key overwrites the previous value.",
          "Immutable keys: keys must be strings, numbers or tuples — never lists or dictionaries.",
          "Values can be of any data type — strings, numbers, lists, even other dictionaries.",
        ]},
        { type: "example", num: "5.33", title: "Creating with Curly Braces",
          code: 'student = {\n    "name": "Aryananda",\n    "age": 17,\n    "class": "12A"\n}\nprint(student)',
          output: "{'name': 'Aryananda', 'age': 17, 'class': '12A'}", explain: null },
        { type: "example", num: "5.34", title: "Creating with dict()",
          code: 'student = dict(name="Sreerag", age=17, class_="CSE")\nprint(student)',
          output: "{'name': 'Sreerag', 'age': 17, 'class_': 'CSE'}",
          explain: "When using dict(), keys must be valid identifiers — no spaces or special characters." },
        { type: "example", num: "5.35", title: "Accessing Dictionary Elements",
          code: 'student = dict(name="Sreenanda", age=17, class_="E1")\nprint(student["name"])\nprint(student.get("age"))',
          output: "Sreenanda\n17", explain: "get() is safer — it returns None if the key doesn't exist, while [ ] raises a KeyError." },
        { type: "example", num: "5.36", title: "Modifying Dictionary Elements",
          code: 'student = dict(name="Sreelakshmi", age=17, class_="XI")\nstudent["age"] = 18        # Update\nstudent["school"] = "SNHSS"  # Add\nprint(student)',
          output: "{'name': 'Sreelakshmi', 'age': 18, 'class_': 'XI', 'school': 'SNHSS'}",
          explain: "Assigning to an existing key updates it; assigning to a new key adds it." },
        { type: "example", num: "5.37", title: "Removing Elements",
          code: 'student = dict(name="Devarag", age=17, class_="XI")\nstudent.pop("class_")     # removes by key\ndel student["age"]        # deletes a key-value pair\nprint(student)\nstudent.clear()           # removes all items\nprint(student)',
          output: "{'name': 'Devarag'}\n{}",
          explain: "pop(key) and del remove a specific pair; popitem() removes the last inserted item; clear() empties the dictionary." },
        { type: "methodsTable", headers: ["Method","Description"], rows: [
          ["get(key)","Returns the value for the key"], ["keys()","Returns a view of all keys"],
          ["values()","Returns a view of all values"], ["items()","Returns a view of all key-value pairs"],
          ["update(dict2)","Updates the dictionary with another dictionary"],
          ["pop(key)","Removes the item with the specified key"], ["popitem()","Removes the last inserted item"],
          ["clear()","Removes all items"], ["copy()","Returns a shallow copy of the dictionary"],
          ["setdefault()","Returns value of a key; sets default if not found"],
        ]},
        { type: "quiz", items: [
          ["What data structure stores key-value pairs?", "Dictionary"],
          ["Which method safely retrieves a value without raising an error?", "get()"],
          ["From which Python version do dicts preserve insertion order?", "3.7"],
          ["Can a list be used as a dictionary key?", "No — keys must be immutable"],
        ]},
      ],
    },
    {
      id: "compare", kicker: "5.3 – 5.6 Recap", title: "List vs Tuple vs Set vs Dictionary",
      lede: "A side-by-side reference for choosing the right data structure.",
      blocks: [
        { type: "compareTable",
          headers: ["Feature","List","Tuple","Set","Dictionary"],
          rows: [
            ["Syntax","[ ]","( )","{ } or set()","{key: value}"],
            ["Mutable","Yes","No","Yes","Yes"],
            ["Ordered (3.7+)","Yes","Yes","No","Yes"],
            ["Indexed","Yes (0-based)","Yes (0-based)","No","No (by key)"],
            ["Allows Duplicates","Yes","Yes","No","Keys: No, Values: Yes"],
            ["Element Access","By index","By index","Not allowed","By key"],
            ["Common Methods","append, insert, pop","count, index","add, remove, union","get, keys, values, items"],
            ["Performance","Slower than tuple","Faster than list","Fast membership test","Fast lookup by key"],
            ["Use Case","General-purpose","Fixed / read-only data","Unique items, set ops","Structured key-value data"],
          ]},
        { type: "sub", text: "Chapter Summary" },
        { type: "list", items: [
          "Control structures manage program flow using conditional and looping statements.",
          "Decision-making constructs: if-elif-else and match-case.",
          "Iterative structures: for and while loops, with break, continue, and else clauses.",
          "Lists — ordered, mutable, allow duplicates; Tuples — ordered, immutable.",
          "Sets — unordered, unique elements; Dictionaries — key-value pairs, fast lookup by key.",
          "Combining control logic with data handling gives students the ability to write structured, efficient and readable programs.",
        ]},
      ],
    },
    {
      id: "practice", kicker: "Test Yourself", title: "Full Question Bank",
      lede: "All 35 questions from the textbook — use these to check your understanding before the exam.",
      blocks: [
        { type: "tyList", items: [
          "How many else blocks can be used in an if structure?",
          "Which symbol represents default case in match-case? (a) *  (b) #  (c) _  (d) %",
          "What is the default start value of range()?",
          "Which statement stops the loop immediately? (a) continue  (b) break  (c) stop  (d) exit",
          "What is the index of the first element in a list?",
          "Which method removes all elements from a list?",
          "Which data structure does not allow duplicates? (a) List  (b) Tuple  (c) Set  (d) Dictionary",
          "What does a & b represent in sets? (a) Union  (b) Intersection  (c) Difference  (d) Symmetric difference",
          "The ______ method safely retrieves a value from a dictionary.",
          "The method used to remove all items from a dictionary is ______.",
          "Write the syntax of if-elif-else statement.",
          "Explain the role of indentation in Python.",
          "Differentiate between for loop and while loop.",
          "What is a nested loop?",
          "Distinguish between break and continue.",
          "What is an infinite loop?",
          "Define list and mention any two characteristics.",
          "What is list slicing? Give an example.",
          "What is a tuple? Why is it called immutable?",
          "Differentiate between list and tuple.",
          "Define a set and mention its key features.",
          "What are set operations? Name any two.",
          "Define dictionary with an example.",
          "How are dictionary elements accessed?",
          "Differentiate between keys and values in a dictionary.",
          "Explain the working of for loop with else using an example.",
          "Explain union and intersection of sets with examples.",
          "Explain different methods used in dictionaries.",
          "Explain the working of match-case with an example.",
          "Write a program to count vowels in a string.",
          "Write a program to print numbers from 1 to 10 using while loop.",
          "Write a program to print multiplication table using nested for loop.",
          "Write a program to demonstrate list operations (append, remove, pop).",
          "Write a program to remove duplicates using a set.",
          "Write a program to create and update a dictionary.",
        ]},
      ],
    },
  ],
};
